### ISSUE TITLE
how to use it on win i can't open it

### ISSUE THREAD

**Issue by xiaoken8713** [selinger/katahex#2]
It flashes when used on win11

**Comment by selinger** [comment]
I don't know what "it flashes" means, and I don't use Windows, so I can't help with this. You'll get better help by asking on Discord, not here.

**Comment by xiaoken8713** [comment]
you haven't replied to the  message I sent you on Discord

**Comment by selinger** [comment]
When I suggested to "ask on Discord", I didn't mean that you should send me a private message there. I meant that there are people on the public Discord channel who use Windows and might be able to help you solve the problem "It flashes when used on win11". I cannot help you with that because I am not a Windows user.
